import { Project } from './project-types';

export const projects: Project[] = [
  {
    id: '1',
    name: 'برنامج الأسر المنتجة',
    organization: 'جمعية البر الخيرية',
    type: 'تنموي',
    category: 'التمكين الاقتصادي',
    status: 'execution',
    budget: 250000,
    duration: '12 شهر',
    startDate: '2026-01-15',
    endDate: '2027-01-15',
    progress: 65,
    manager: 'أحمد محمد',
    description:
      'برنامج لتمكين الأسر المحتاجة اقتصادياً من خلال تدريبهم على مهارات إنتاجية وتوفير التمويل اللازم',
    beneficiaries: '150 أسرة',
    geographicScope: 'مدينة الرياض',
    lastUpdated: '2026-06-05',
    version: 3,
    health: 'good',
  },
  {
    id: '2',
    name: 'مشروع كفالة الأيتام',
    organization: 'مؤسسة الرعاية الاجتماعية',
    type: 'خيري',
    category: 'كفالة ورعاية',
    status: 'funded',
    budget: 500000,
    duration: '24 شهر',
    startDate: '2026-02-01',
    endDate: '2028-02-01',
    progress: 30,
    manager: 'فاطمة أحمد',
    description:
      'برنامج كفالة ورعاية شاملة للأيتام تشمل التعليم والصحة والسكن',
    beneficiaries: '200 يتيم',
    geographicScope: 'المنطقة الشرقية',
    lastUpdated: '2026-06-06',
    version: 2,
    health: 'excellent',
  },
  {
    id: '3',
    name: 'برنامج التدريب المهني',
    organization: 'جمعية التنمية المجتمعية',
    type: 'تدريبي',
    category: 'التعليم والتدريب',
    status: 'pm-approval',
    budget: 180000,
    duration: '8 أشهر',
    startDate: '2026-03-01',
    endDate: '2026-11-01',
    progress: 0,
    manager: 'خالد سعيد',
    description: 'تدريب الشباب على المهارات المهنية المطلوبة في سوق العمل',
    beneficiaries: '100 متدرب',
    geographicScope: 'جدة',
    lastUpdated: '2026-06-07',
    version: 1,
    health: 'good',
  },
  {
    id: '4',
    name: 'مبادرة الإفطار الصباحي',
    organization: 'جمعية الخير',
    type: 'إغاثي',
    category: 'الإغاثة الإنسانية',
    status: 'charity-review',
    budget: 120000,
    duration: '6 أشهر',
    startDate: '2026-04-01',
    endDate: '2026-10-01',
    progress: 0,
    manager: 'سارة علي',
    description: 'توفير وجبات إفطار صحية للطلاب المحتاجين في المدارس',
    beneficiaries: '500 طالب',
    geographicScope: 'المدينة المنورة',
    lastUpdated: '2026-06-07',
    version: 1,
    health: 'at-risk',
  },
  {
    id: '5',
    name: 'مشروع الرعاية الصحية المتنقلة',
    organization: 'مؤسسة الصحة للجميع',
    type: 'صحي',
    category: 'الرعاية الصحية',
    status: 'draft',
    budget: 350000,
    duration: '18 شهر',
    startDate: '2026-05-01',
    endDate: '2027-11-01',
    progress: 0,
    manager: 'محمد عبدالله',
    description:
      'عيادات صحية متنقلة لخدمة المناطق النائية وتقديم الرعاية الصحية الأولية',
    beneficiaries: '3000 مستفيد',
    geographicScope: 'القصيم',
    lastUpdated: '2026-06-07',
    version: 1,
    health: 'good',
  },
];

export function findProjectById(id: string | undefined): Project | undefined {
  return projects.find((p) => p.id === id);
}
